name: Extract data from API, load to Google

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
# on:
#   schedule:
#     - cron:  '0 9 * * SUN'

# manual trigger
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "extract"      
  extract:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'write'
      id-token: 'write'
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # FIRST step (always do this!): checkout repo to github runner
    - name: Check out repository code
      uses: actions/checkout@v4 # Use the official action
    
    # set up Python version
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    # install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
      
    # authenticate with Google Cloudn
    - uses: 'google-github-actions/auth@v3'
      with:
        project_id: 'solren-view-etl'
        workload_identity_provider: 'projects/924342529586/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: 'solren-view-etl@appspot.gserviceaccount.com' #

    # Runs a single command using the runners shell
    - name: Run extraction script
      run: python ./extract.py

    # Push changes from Github runner back to repo (start_date.txt file)
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add {start_date.txt,logs.txt}
        git commit -m "(Github Actions) Update start.txt and logs.txt" || echo "No changes to commit"
        git push
